id: 4
name: LibraryTestTwo
description: The variable group that contains the application staging environment values
preffix: LibraryTestTwo_
variables:
- name: VariableOne
  value: test
- name: VariableTwo
  value: test
- name: VariableThree
  value: test